version: "1.0"
type: component
data:
  name: omv-services-restic-settings-form-page
  type: formPage
  config:
    request:
      service: Restic
      get:
        method: getSettings
      post:
        method: setSettings
    fields:
      - type: textInput
        name: cachedir
        label: _("Cache directory")
        value: "/var/cache/restic"
        hint: _("Directory where Restic stores its local cache. The cache speeds up operations, especially for remote repositories. Leave blank to disable caching (not recommended).")
    buttons:
      - template: submit
